# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd7677c72a4a12c694611ea8779d87d1a4e556e0417785052dbf8995a6e9fbd0c8ed1ffeac58feaca422d0ffe3c9966a2b616757312f88eadc97137346d5165

test:
  secret_key_base: a4de5b2268b3814a306e285516dff3581dcfde5beea91a796c75578407902f0dc8ebc8f5105aadf55da0df180daa71f6accf953b8d82692f393da19ae0e505f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
